Points calculation
NetumFi/Tietosuojatesti pull request #53
Opened 2017-06-30 13:15 UTC by he1kki

2017-07-04 07:03 UTC, hollannikas requested changes

2017-07-04 07:03 UTC, hollannikas commented on src/app/backing-up-from-results-not-allowed-guard.ts
> +    const access = !this.previousPageResultsOrUndefined || route.url.toString().indexOf('kysymykset') === -1;
Can you not handle this with _only_ the provided router snapshots? That way canActivate is a pure function.

2017-07-04 07:03 UTC, hollannikas commented on src/app/backing-up-from-results-not-allowed-guard.ts
> +export class BackingUpFromResultsNotAllowedGuard implements CanActivate {
As much as I am all for explicit naming, this is a bit on the long side.

2017-07-04 07:04 UTC, hollannikas commented
It might be good to change my "Ammend me" commit to a more descriptive comment. I left it like that as a reminder for myself to ammed that commit (and change the comment) 😉

2017-07-05 10:19 UTC, hollannikas requested changes

2017-07-05 10:19 UTC, hollannikas commented on src/app/questions/questions.component.ts
> +
This seems to always be an array of one 😀  Please change this to `subscription: Subscription`

2017-07-05 10:19 UTC, hollannikas commented on src/app/reducers/questions.ts
>        const newState = {
This is a bit overcomplicated for a simple replace. Why not group the answers per question, for example `{ questionId: Answer[] }` or something? That way you can use something like `allAnswers[questionId] = replacingAnswers`

2017-07-05 10:33 UTC, he1kki commented on src/app/questions/questions.component.ts
> +
I'll change it. I just like it because it takes care of all subscriptions regardless of the amount.

2017-07-05 12:09 UTC, merged